apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: nextjs-app
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - port: 3000          # Service port
      targetPort: 3000    # Container port
      nodePort: 30000     # NodePort inside the cluster
